### ISSUE TITLE
Blank Addon on New Character

### ISSUE THREAD

**Issue by nator316** [zetas/GatherBuddyImproved#4]
Ive got a made character in which everythings fine but when I create a new character with addon on, the addon is blank no herbs appear even if im near them. Top left corner theres an addon below thats its your addon but invisible since no plant appear even if near them.
![liz 140821 081519](https://cloud.githubusercontent.com/assets/8525989/4015455/fa31b8ea-2a2a-11e4-8f5f-5bb540ef6990.png)

**Comment by zetas** [comment]
Here's what happens when you first run GBI:
1. It pulls a list of all your currently known tradeskills related to harvesting
2. Enables display for any harvestables that require your known tradeskills
3. Hide everything else

So, on a new character, with no harvestable tradeskills known (except farming at level 7 or so) you won't see anything by default on GBI. You may of course open the config window and enable anything and everything to be displayed regardless of your skills.

Now, I have a fix in the pipeline to periodically check for new tradeskills and show that harvestable category when one is learned but I haven't gotten around to implementing it yet. For the meantime It'll have to be manual.
